### ISSUE TITLE
The XKCD image license is CC-BY-NC

### ISSUE THREAD

**Issue by Pomax** [PayDevs/awful-oss-incidents#1]
Just to prevent some poignant irony: XKCD images are licensed as CC-BY-NC 2.5 (see https://xkcd.com/license.html), and there doesn't appear to be an attribution caption, which is only allowed if you fairly paid XKCD for the use of that image =)

(but it's probably a matter of just having forgotten to add the attribution ;)

**Comment by joergrech** [comment]
Thanks for the Tip!
